yarn entity:complete User
yarn entity:complete Admin
yarn entity:complete Customer
yarn entity:complete Manager
yarn entity:complete Valet
yarn entity:complete Company
yarn entity:complete Garage
yarn entity:complete Address
yarn entity:complete Slot
yarn entity:complete Booking
yarn entity:complete ValetAssignment
yarn entity:complete BookingTimeline
yarn entity:complete Verification
yarn entity:complete Review
